## Deliverable 3. Create a Travel Itinerary Map.

In [23]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [24]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(10)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Avarua,CK,80.65,overcast clouds,-21.2078,-159.7750,Paradise Inn
1,1,Salinopolis,BR,78.37,clear sky,-0.6136,-47.3561,Salinas Park Resort Maçarico AP101
2,4,East London,ZA,75.56,overcast clouds,-33.0153,27.9116,Tu Casa
3,10,Victoria,HK,87.85,overcast clouds,22.2855,114.1577,Mini Central
4,11,Los Llanos De Aridane,ES,65.95,overcast clouds,28.6585,-17.9182,Valle Aridane
5,13,Semirom,IR,64.06,clear sky,31.4167,51.5667,Motel Dena
6,17,Bethel,US,67.62,broken clouds,41.3712,-73.4140,Courtyard by Marriott Danbury
7,18,Kinablangan,PH,84.99,overcast clouds,7.6947,126.5503,Morales Eatery and Lodging House
8,19,Mandalgovi,MN,68.97,scattered clouds,45.7625,106.2708,В.Ганбат
9,20,Vaini,TO,82.56,smoke,-21.2000,-175.2000,Keleti Beach Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Goose Creek")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Goose Creek")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Mount Pleasant")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Hilton Head Island")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Wilmington Island")]

In [29]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_df.loc[(vacation_df["City"] == "Goose Creek")].to_numpy()
end = vacation_df.loc[(vacation_df["City"] == "Goose Creek")].to_numpy()
stop1 = vacation_df.loc[(vacation_df["City"] == "Mount Pleasant")].to_numpy()
stop2 = vacation_df.loc[(vacation_df["City"] == "Hilton Head Island")].to_numpy()
stop3 = vacation_df.loc[(vacation_df["City"] == "Wilmington Island")].to_numpy()

In [31]:
array = ['Goose Creek', 'Mount Pleasant', 'Hilton Head Island', 'Wilmington Island']
vacation_df.loc[vacation_df['City'].isin(array)]

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
275,455,Wilmington Island,US,81.99,clear sky,32.0036,-80.9737,Breezeway Studio Manor LLC
335,553,Mount Pleasant,US,81.00,mist,32.7941,-79.8626,Best Western Patriots Point
352,583,Goose Creek,US,80.89,scattered clouds,32.9810,-80.0326,"Holiday Inn Express & Suites Charleston-North,..."
399,650,Hilton Head Island,US,82.45,broken clouds,32.2163,-80.7526,Disney’s Hilton Head Island Resort

In [36]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps.datasets
goose_creek = (32.9810, -80.0326)
mount_pleasant = (32.7941, -79.8626)
hilton_head_island = (32.2163, -80.7526)
wilmington_island = (32.0036, -80.9737)

fig = gmaps.figure()
goose2wilmington = gmaps.directions_layer(
        goose_creek, goose_creek, waypoints=[mount_pleasant, hilton_head_island, wilmington_island],
        travel_mode='DRIVING')
fig.add_layer(goose2wilmington)
fig

Figure(layout=FigureLayout(height='420px'))

In [45]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,583,Goose Creek,US,80.89,scattered clouds,32.9810,-80.0326,"Holiday Inn Express & Suites Charleston-North,..."
1,553,Mount Pleasant,US,81.00,mist,32.7941,-79.8626,Best Western Patriots Point
2,650,Hilton Head Island,US,82.45,broken clouds,32.2163,-80.7526,Disney’s Hilton Head Island Resort
3,455,Wilmington Island,US,81.99,clear sky,32.0036,-80.9737,Breezeway Studio Manor LLC

In [46]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [51]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))